/**
 * Centralized enum values shared between Mongoose schemas, Joi validators,
 * services, and controllers.
 */

export const ROLES = Object.freeze({
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
});

export const TRANSACTION_STATUS = Object.freeze({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  BLOCKED: "BLOCKED",
});

export const FRAUD_DECISION = Object.freeze({
  COMPLETED: "COMPLETED",
  VERIFICATION_REQUIRED: "VERIFICATION_REQUIRED",
  BLOCKED: "BLOCKED",
});

export const RISK_LEVEL = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
});

export const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  FROZEN: "FROZEN",
  CLOSED: "CLOSED",
});

export const ACCOUNT_TYPE = Object.freeze({
  SAVINGS: "SAVINGS",
  CURRENT: "CURRENT",
});

export const FRAUD_LOG_REVIEW_STATUS = Object.freeze({
  OPEN: "OPEN",
  REVIEWED: "REVIEWED",
  DISMISSED: "DISMISSED",
});

export const ML_SERVICE_STATUS = Object.freeze({
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE: "UNAVAILABLE",
  INVALID_RESPONSE: "INVALID_RESPONSE",
});

export const SECURITY_EVENTS = Object.freeze({
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  OTP_ISSUED: "OTP_ISSUED",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_FAILED: "OTP_FAILED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  BENEFICIARY_ADDED: "BENEFICIARY_ADDED",
  BENEFICIARY_REMOVED: "BENEFICIARY_REMOVED",
  TRANSFER_INITIATED: "TRANSFER_INITIATED",
  TRANSFER_COMPLETED: "TRANSFER_COMPLETED",
  TRANSFER_VERIFICATION_REQUIRED: "TRANSFER_VERIFICATION_REQUIRED",
  TRANSFER_BLOCKED: "TRANSFER_BLOCKED",
  NEW_DEVICE_SEEN: "NEW_DEVICE_SEEN",
  ACCOUNT_OPENED: "ACCOUNT_OPENED",
  ACCOUNT_PRIMARY_CHANGED: "ACCOUNT_PRIMARY_CHANGED",
});

export const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  BENEFICIARY_ADDED: "BENEFICIARY_ADDED",
  BENEFICIARY_UPDATED: "BENEFICIARY_UPDATED",
  BENEFICIARY_REMOVED: "BENEFICIARY_REMOVED",
  TRANSFER_INITIATED: "TRANSFER_INITIATED",
  TRANSFER_COMPLETED: "TRANSFER_COMPLETED",
  TRANSFER_VERIFICATION_REQUIRED: "TRANSFER_VERIFICATION_REQUIRED",
  TRANSFER_BLOCKED: "TRANSFER_BLOCKED",
  ADMIN_BLOCKED_USER: "ADMIN_BLOCKED_USER",
  ADMIN_UNBLOCKED_USER: "ADMIN_UNBLOCKED_USER",
  ADMIN_REVIEWED_FRAUD: "ADMIN_REVIEWED_FRAUD",
  ACCOUNT_OPENED: "ACCOUNT_OPENED",
  ACCOUNT_PRIMARY_CHANGED: "ACCOUNT_PRIMARY_CHANGED",
});

/**
 * Batch 6 — In-app notification types.
 */
export const NOTIFICATION_TYPES = Object.freeze({
  TRANSFER_COMPLETED: "TRANSFER_COMPLETED",
  TRANSFER_VERIFICATION_REQUIRED: "TRANSFER_VERIFICATION_REQUIRED",
  TRANSFER_BLOCKED: "TRANSFER_BLOCKED",
  FD_CREATED: "FD_CREATED",
  FD_MATURED: "FD_MATURED",
  PPF_ACCOUNT_OPENED: "PPF_ACCOUNT_OPENED",
  PPF_CONTRIBUTION: "PPF_CONTRIBUTION",
  SECURITY_ALERT: "SECURITY_ALERT",
  STATEMENT_READY: "STATEMENT_READY",
});

export const NOTIFICATION_PRIORITY = Object.freeze({
  INFO: "INFO",
  SUCCESS: "SUCCESS",
  WARNING: "WARNING",
  DANGER: "DANGER",
});

/**
 * NexusBank internal-bank namespace.
 */
export const NEXUSBANK_IFSC_PREFIX = "NEXB0";